# Imagen oficial de apache con php
FROM php:8.2-apache 

# Instalar extensión PDO MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Especifico el directorio de trabajo dentro del contenedor
WORKDIR /var/www/html

# Dar permisos
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html